# Generated by Django 3.2.25 on 2025-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_photos/', verbose_name='Фото меню')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание (необязательно)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Фото основного меню',
                'verbose_name_plural': 'Фото основного меню',
                'ordering': ['-created_at'],
            },
        ),
    ]
