# Generated by Django 3.2.25 on 2025-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='+7 (000) 000-00-00', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
