# Generated by Django 3.2.25 on 2025-07-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
