# Generated by Django 3.2.25 on 2025-07-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail_content',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание'),
        ),
    ]
