# Generated by Django 3.2.25 on 2025-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_news_detail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuphoto',
            name='category',
            field=models.CharField(choices=[('interior', 'Интерьер'), ('dish', 'Блюда')], default='dish', max_length=20, verbose_name='Категория'),
        ),
    ]
