# Generated by Django 3.2.25 on 2025-07-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_menuphoto_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('interior', 'Интерьер'), ('dish', 'Блюда')], max_length=20)),
            ],
        ),
    ]
